cp /home/user/S23/kernel_platform/common/arch/arm64/include/asm/pgtable-prot.h kernel_platform/common/arch/arm64/include/asm/pgtable-prot.h
cp /home/user/S23/kernel_platform/common/arch/arm64/include/asm/pgtable.h kernel_platform/common/arch/arm64/include/asm/pgtable.h
cp /home/user/S23/kernel_platform/common/arch/arm64/include/uapi/asm/setup.h kernel_platform/common/arch/arm64/include/uapi/asm/setup.h
cp /home/user/S23/kernel_platform/common/arch/arm64/kernel/image.h kernel_platform/common/arch/arm64/kernel/image.h
cp /home/user/S23/kernel_platform/common/arch/arm64/kernel/setup.c kernel_platform/common/arch/arm64/kernel/setup.c
cp /home/user/S23/kernel_platform/common/arch/arm64/kernel/syscall.c kernel_platform/common/arch/arm64/kernel/syscall.c
cp /home/user/S23/kernel_platform/common/arch/arm64/kernel/vmlinux.lds.S kernel_platform/common/arch/arm64/kernel/vmlinux.lds.S
cp /home/user/S23/kernel_platform/common/arch/arm64/mm/mmu.c kernel_platform/common/arch/arm64/mm/mmu.c
cp /home/user/S23/kernel_platform/common/arch/arm64/mm/pgd.c kernel_platform/common/arch/arm64/mm/pgd.c
cp /home/user/S23/kernel_platform/common/arch/um/include/asm/common.lds.S kernel_platform/common/arch/um/include/asm/common.lds.S
cp /home/user/S23/kernel_platform/common/arch/um/include/asm/io.h kernel_platform/common/arch/um/include/asm/io.h
cp /home/user/S23/kernel_platform/common/block/ioctl.c kernel_platform/common/block/ioctl.c
cp /home/user/S23/kernel_platform/common/drivers/base/power/wakeup.c kernel_platform/common/drivers/base/power/wakeup.c
cp /home/user/S23/kernel_platform/common/drivers/block/zram/zcomp.h kernel_platform/common/drivers/block/zram/zcomp.h
cp /home/user/S23/kernel_platform/common/drivers/block/zram/zram_drv.c kernel_platform/common/drivers/block/zram/zram_drv.c
cp /home/user/S23/kernel_platform/common/drivers/block/zram/zram_drv.h kernel_platform/common/drivers/block/zram/zram_drv.h
cp /home/user/S23/kernel_platform/common/drivers/connector/cn_proc.c kernel_platform/common/drivers/connector/cn_proc.c
cp /home/user/S23/kernel_platform/common/drivers/hid/hid-apple.c kernel_platform/common/drivers/hid/hid-apple.c
cp /home/user/S23/kernel_platform/common/drivers/hid/hid-samsung.c kernel_platform/common/drivers/hid/hid-samsung.c
cp /home/user/S23/kernel_platform/common/drivers/hid/uhid.c kernel_platform/common/drivers/hid/uhid.c
cp /home/user/S23/kernel_platform/common/drivers/hid/usbhid/hid-core.c kernel_platform/common/drivers/hid/usbhid/hid-core.c
cp /home/user/S23/kernel_platform/common/drivers/hid/usbhid/usbhid.h kernel_platform/common/drivers/hid/usbhid/usbhid.h
cp /home/user/S23/kernel_platform/common/drivers/input/evdev.c kernel_platform/common/drivers/input/evdev.c
cp /home/user/S23/kernel_platform/common/drivers/phy/phy-core.c kernel_platform/common/drivers/phy/phy-core.c
cp /home/user/S23/kernel_platform/common/drivers/usb/core/driver.c kernel_platform/common/drivers/usb/core/driver.c
cp /home/user/S23/kernel_platform/common/drivers/usb/core/usb.h kernel_platform/common/drivers/usb/core/usb.h
cp /home/user/S23/kernel_platform/common/drivers/usb/gadget/function/f_acm.c kernel_platform/common/drivers/usb/gadget/function/f_acm.c
cp /home/user/S23/kernel_platform/common/drivers/usb/storage/debug.h kernel_platform/common/drivers/usb/storage/debug.h
cp /home/user/S23/kernel_platform/common/drivers/usb/storage/transport.c kernel_platform/common/drivers/usb/storage/transport.c
cp /home/user/S23/kernel_platform/common/drivers/usb/storage/usb.c kernel_platform/common/drivers/usb/storage/usb.c
cp /home/user/S23/kernel_platform/common/fs/crypto/crypto.c kernel_platform/common/fs/crypto/crypto.c
cp /home/user/S23/kernel_platform/common/fs/d_path.c kernel_platform/common/fs/d_path.c
cp /home/user/S23/kernel_platform/common/fs/erofs/super.c kernel_platform/common/fs/erofs/super.c
cp /home/user/S23/kernel_platform/common/fs/fat/fat.h kernel_platform/common/fs/fat/fat.h
cp /home/user/S23/kernel_platform/common/fs/fat/inode.c kernel_platform/common/fs/fat/inode.c
cp /home/user/S23/kernel_platform/common/fs/fat/misc.c kernel_platform/common/fs/fat/misc.c
cp /home/user/S23/kernel_platform/common/fs/fcntl.c kernel_platform/common/fs/fcntl.c
cp /home/user/S23/kernel_platform/common/fs/mount.h kernel_platform/common/fs/mount.h
cp /home/user/S23/kernel_platform/common/fs/mpage.c kernel_platform/common/fs/mpage.c
cp /home/user/S23/kernel_platform/common/fs/pnode.h kernel_platform/common/fs/pnode.h
cp /home/user/S23/kernel_platform/common/fs/proc/internal.h kernel_platform/common/fs/proc/internal.h
cp /home/user/S23/kernel_platform/common/fs/proc/meminfo.c kernel_platform/common/fs/proc/meminfo.c
cp /home/user/S23/kernel_platform/common/fs/timerfd.c kernel_platform/common/fs/timerfd.c
cp /home/user/S23/kernel_platform/common/include/dt-bindings/input/linux-event-codes.h kernel_platform/common/include/dt-bindings/input/linux-event-codes.h
cp /home/user/S23/kernel_platform/common/include/kunit/test.h kernel_platform/common/include/kunit/test.h
cp /home/user/S23/kernel_platform/common/include/linux/backing-dev-defs.h kernel_platform/common/include/linux/backing-dev-defs.h
cp /home/user/S23/kernel_platform/common/include/linux/bio.h kernel_platform/common/include/linux/bio.h
cp /home/user/S23/kernel_platform/common/include/linux/cleancache.h kernel_platform/common/include/linux/cleancache.h
cp /home/user/S23/kernel_platform/common/include/linux/cred.h kernel_platform/common/include/linux/cred.h
cp /home/user/S23/kernel_platform/common/include/linux/delayacct.h kernel_platform/common/include/linux/delayacct.h
cp /home/user/S23/kernel_platform/common/include/linux/fbcon.h kernel_platform/common/include/linux/fbcon.h
cp /home/user/S23/kernel_platform/common/include/linux/gfp.h kernel_platform/common/include/linux/gfp.h
cp /home/user/S23/kernel_platform/common/include/linux/highmem.h kernel_platform/common/include/linux/highmem.h
cp /home/user/S23/kernel_platform/common/include/linux/init_task.h kernel_platform/common/include/linux/init_task.h
cp /home/user/S23/kernel_platform/common/include/linux/iommu.h kernel_platform/common/include/linux/iommu.h
cp /home/user/S23/kernel_platform/common/include/linux/khugepaged.h kernel_platform/common/include/linux/khugepaged.h
cp /home/user/S23/kernel_platform/common/include/linux/memblock.h kernel_platform/common/include/linux/memblock.h
cp /home/user/S23/kernel_platform/common/include/linux/mount.h kernel_platform/common/include/linux/mount.h
cp /home/user/S23/kernel_platform/common/include/linux/notifier.h kernel_platform/common/include/linux/notifier.h
cp /home/user/S23/kernel_platform/common/include/linux/pagemap.h kernel_platform/common/include/linux/pagemap.h
cp /home/user/S23/kernel_platform/common/include/linux/vmstat.h kernel_platform/common/include/linux/vmstat.h
cp /home/user/S23/kernel_platform/common/include/net/netfilter/nf_conntrack.h kernel_platform/common/include/net/netfilter/nf_conntrack.h
cp /home/user/S23/kernel_platform/common/include/scsi/scsi_host.h kernel_platform/common/include/scsi/scsi_host.h
cp /home/user/S23/kernel_platform/common/include/trace/events/android_fs.h kernel_platform/common/include/trace/events/android_fs.h
cp /home/user/S23/kernel_platform/common/include/trace/events/android_fs_template.h kernel_platform/common/include/trace/events/android_fs_template.h
cp /home/user/S23/kernel_platform/common/include/trace/events/mmflags.h kernel_platform/common/include/trace/events/mmflags.h
cp /home/user/S23/kernel_platform/common/include/uapi/asm-generic/mman-common.h kernel_platform/common/include/uapi/asm-generic/mman-common.h
cp /home/user/S23/kernel_platform/common/include/uapi/asm-generic/socket.h kernel_platform/common/include/uapi/asm-generic/socket.h
cp /home/user/S23/kernel_platform/common/include/uapi/linux/f2fs.h kernel_platform/common/include/uapi/linux/f2fs.h
cp /home/user/S23/kernel_platform/common/include/uapi/linux/fs.h kernel_platform/common/include/uapi/linux/fs.h
cp /home/user/S23/kernel_platform/common/include/uapi/linux/if_tun.h kernel_platform/common/include/uapi/linux/if_tun.h
cp /home/user/S23/kernel_platform/common/include/uapi/linux/input-event-codes.h kernel_platform/common/include/uapi/linux/input-event-codes.h
cp /home/user/S23/kernel_platform/common/include/uapi/linux/magic.h kernel_platform/common/include/uapi/linux/magic.h
cp /home/user/S23/kernel_platform/common/init/init_task.c kernel_platform/common/init/init_task.c
cp /home/user/S23/kernel_platform/common/kernel/audit.c kernel_platform/common/kernel/audit.c
cp /home/user/S23/kernel_platform/common/kernel/cgroup/legacy_freezer.c kernel_platform/common/kernel/cgroup/legacy_freezer.c
cp /home/user/S23/kernel_platform/common/kernel/cred.c kernel_platform/common/kernel/cred.c
cp /home/user/S23/kernel_platform/common/kernel/delayacct.c kernel_platform/common/kernel/delayacct.c
cp /home/user/S23/kernel_platform/common/kernel/dma/contiguous.c kernel_platform/common/kernel/dma/contiguous.c
cp /home/user/S23/kernel_platform/common/kernel/power/suspend.c kernel_platform/common/kernel/power/suspend.c
cp /home/user/S23/kernel_platform/common/kernel/rcu/rcu.h kernel_platform/common/kernel/rcu/rcu.h
cp /home/user/S23/kernel_platform/common/kernel/rcu/srcutiny.c kernel_platform/common/kernel/rcu/srcutiny.c
cp /home/user/S23/kernel_platform/common/kernel/rcu/srcutree.c kernel_platform/common/kernel/rcu/srcutree.c
cp /home/user/S23/kernel_platform/common/kernel/rcu/tiny.c kernel_platform/common/kernel/rcu/tiny.c
cp /home/user/S23/kernel_platform/common/kernel/rcu/update.c kernel_platform/common/kernel/rcu/update.c
cp /home/user/S23/kernel_platform/common/kernel/reboot.c kernel_platform/common/kernel/reboot.c
cp /home/user/S23/kernel_platform/common/kernel/time/sched_clock.c kernel_platform/common/kernel/time/sched_clock.c
cp /home/user/S23/kernel_platform/common/kernel/time/timekeeping_debug.c kernel_platform/common/kernel/time/timekeeping_debug.c
cp /home/user/S23/kernel_platform/common/kernel/umh.c kernel_platform/common/kernel/umh.c
cp /home/user/S23/kernel_platform/common/lib/kunit/executor.c kernel_platform/common/lib/kunit/executor.c
cp /home/user/S23/kernel_platform/common/lib/kunit/kunit-example-test.c kernel_platform/common/lib/kunit/kunit-example-test.c
cp /home/user/S23/kernel_platform/common/lib/kunit/string-stream-test.c kernel_platform/common/lib/kunit/string-stream-test.c
cp /home/user/S23/kernel_platform/common/lib/kunit/string-stream.c kernel_platform/common/lib/kunit/string-stream.c
cp /home/user/S23/kernel_platform/common/lib/kunit/test.c kernel_platform/common/lib/kunit/test.c
cp /home/user/S23/kernel_platform/common/lib/show_mem.c kernel_platform/common/lib/show_mem.c
cp /home/user/S23/kernel_platform/common/mm/cleancache.c kernel_platform/common/mm/cleancache.c
cp /home/user/S23/kernel_platform/common/mm/memblock.c kernel_platform/common/mm/memblock.c
cp /home/user/S23/kernel_platform/common/mm/page_io.c kernel_platform/common/mm/page_io.c
cp /home/user/S23/kernel_platform/common/mm/process_vm_access.c kernel_platform/common/mm/process_vm_access.c
cp /home/user/S23/kernel_platform/common/mm/slab.h kernel_platform/common/mm/slab.h
cp /home/user/S23/kernel_platform/common/mm/zswap.c kernel_platform/common/mm/zswap.c
cp /home/user/S23/kernel_platform/common/net/mac80211/agg-rx.c kernel_platform/common/net/mac80211/agg-rx.c
cp /home/user/S23/kernel_platform/common/net/mac80211/mesh.c kernel_platform/common/net/mac80211/mesh.c
cp /home/user/S23/kernel_platform/common/net/mac80211/mesh_hwmp.c kernel_platform/common/net/mac80211/mesh_hwmp.c
cp /home/user/S23/kernel_platform/common/net/mac80211/mesh_plink.c kernel_platform/common/net/mac80211/mesh_plink.c
cp /home/user/S23/kernel_platform/common/net/mac80211/mesh_sync.c kernel_platform/common/net/mac80211/mesh_sync.c
cp /home/user/S23/kernel_platform/common/net/mac80211/tdls.c kernel_platform/common/net/mac80211/tdls.c
cp /home/user/S23/kernel_platform/common/net/mac80211/util.c kernel_platform/common/net/mac80211/util.c
cp /home/user/S23/kernel_platform/common/scripts/dtc/include-prefixes/dt-bindings/input/linux-event-codes.h kernel_platform/common/scripts/dtc/include-prefixes/dt-bindings/input/linux-event-codes.h
cp /home/user/S23/kernel_platform/common/security/integrity/iint.c kernel_platform/common/security/integrity/iint.c
cp /home/user/S23/kernel_platform/common/security/integrity/integrity.h kernel_platform/common/security/integrity/integrity.h
cp /home/user/S23/kernel_platform/common/security/selinux/include/objsec.h kernel_platform/common/security/selinux/include/objsec.h
cp /home/user/S23/kernel_platform/common/tools/testing/kunit/kunit.py kernel_platform/common/tools/testing/kunit/kunit.py
cp /home/user/S23/kernel_platform/common/tools/testing/kunit/kunit_config.py kernel_platform/common/tools/testing/kunit/kunit_config.py
cp /home/user/S23/kernel_platform/common/tools/testing/kunit/kunit_kernel.py kernel_platform/common/tools/testing/kunit/kunit_kernel.py
